### PR TITLE
pulling new files

### PR DESCRIPTION
**Pull request by scshiv29-dev**
### **What does this PR do?**

- [x] This pull request fixes bug/error
- [ ] This pull request includes new commands or features
- [ ] This pull request renames args or commands or files
- [ ] This pull request improves code quality
- [ ] This pull request includes non-code changes (README.md, lang.json etc.)

### Status

- [ ] Code changes have been tested
- [x] Code changes work without errors

### CODE REVIEW

**Comment by scshiv29-dev** [comment]
t

**Comment by xCrypt0r** [comment]
@scshiv29-dev This PR will make conflicts why does this PR need?

**Comment by scshiv29-dev** [comment]
I thought these are the new code for the files! And hence asked for a pull request

**Comment by xCrypt0r** [comment]
@scshiv29-dev Don't mind. Branch 'jsdoc' will be removed cause it's unnecessary

**Pull request closed without merging**
